-- REGLA mobile: migrations 0012 + 0013 + 0014 combined. Paste into Supabase SQL Editor and Run. Idempotent.


-- ===================== 0012_mobile_client.sql =====================

-- =====================================================================
-- REGLA · 0012 — Mobile client app (QuintoAndar-style "propostas")
-- Paste into Supabase Dashboard → SQL Editor → Run.  Idempotent.
-- =====================================================================
-- Adds the tables behind the REGLA client app (apps/client) and the realtor
-- app (apps/realtor). Row shapes mirror packages/shared/src/types.ts:
--   client_profiles  ↔ ClientProfile      ("meu cadastro")
--   applications     ↔ Application        (proposta on a listing)
--   client_documents ↔ ClientDocument     (files in bucket 'client-documents')
--   favorites        ↔ Favorite
--
-- Roles: realtors = admins (public.is_admin(), 0010). Clients = any other
-- authenticated user.
--
-- What clients can already do via EXISTING policies (no change needed):
--   * read live listings      — "listings: public reads live" (0001) has no
--                                `to` role, so it applies to authenticated too
--   * read listing photos     — "photos: public reads" (0001), same reasoning
--   * send an inquiry         — "inquiries: public inserts" (0001), no role;
--                                SELECT stays admin-only (api.ts never selects back)
--   * book / list own visits  — "showings: visitor books own" + "showings:
--                                visitor reads own" (0010); api.bookVisit inserts
--                                type='private', status='scheduled', created_by=uid
-- =====================================================================

-- ─── 1. client_profiles ───────────────────────────────────────────────

create table if not exists public.client_profiles (
    user_id          uuid primary key references auth.users(id) on delete cascade,
    full_name        text not null,
    email            text not null,
    phone            text not null,
    cpf              text,
    birth_date       date,
    occupation       text,
    employment_type  text check (employment_type in
                         ('clt','autonomo','empresario','servidor','aposentado','estudante','outro')),
    monthly_income   bigint check (monthly_income >= 0),
    residents        smallint not null default 1 check (residents between 1 and 20),
    has_pets         boolean not null default false,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);

drop trigger if exists client_profiles_set_updated_at on public.client_profiles;
create trigger client_profiles_set_updated_at
    before update on public.client_profiles
    for each row execute function public.set_updated_at();

alter table public.client_profiles enable row level security;

drop policy if exists "client_profiles: owner select" on public.client_profiles;
drop policy if exists "client_profiles: owner insert" on public.client_profiles;
drop policy if exists "client_profiles: owner update" on public.client_profiles;
drop policy if exists "client_profiles: admin select" on public.client_profiles;

create policy "client_profiles: owner select" on public.client_profiles
    for select to authenticated using (user_id = auth.uid());

create policy "client_profiles: owner insert" on public.client_profiles
    for insert to authenticated with check (user_id = auth.uid());

create policy "client_profiles: owner update" on public.client_profiles
    for update to authenticated
    using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "client_profiles: admin select" on public.client_profiles
    for select to authenticated using (public.is_admin());

-- ─── 2. applications ("propostas") ────────────────────────────────────

create table if not exists public.applications (
    id              bigint generated by default as identity primary key,
    listing_id      bigint not null references public.listings(id) on delete cascade,
    -- FK to client_profiles (not auth.users) so PostgREST can embed
    -- `client_profiles(*)` from applications (api.fetchApplicationsForReview).
    user_id         uuid not null references public.client_profiles(user_id) on delete cascade,
    intent          text not null check (intent in ('rent','buy')),
    offered_price   bigint not null check (offered_price > 0),
    guarantee_type  text check (guarantee_type in
                        ('seguro_fianca','fiador','caucao','titulo_capitalizacao','sem_garantia')),
    move_in_date    date,
    message         text,
    status          text not null default 'submitted' check (status in
                        ('submitted','under_review','docs_requested','approved','rejected','withdrawn')),
    reviewer_note   text,
    reviewed_by     uuid references auth.users(id) on delete set null,
    inquiry_id      bigint references public.inquiries(id) on delete set null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists applications_user_idx    on public.applications (user_id, created_at desc);
create index if not exists applications_listing_idx on public.applications (listing_id);
create index if not exists applications_status_idx  on public.applications (status, created_at desc);
create index if not exists applications_inquiry_idx on public.applications (inquiry_id);
create index if not exists applications_reviewer_idx on public.applications (reviewed_by);

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at
    before update on public.applications
    for each row execute function public.set_updated_at();

-- 2a. Non-admins may only withdraw their own (still open) application.
create or replace function public.applications_guard_client_update()
returns trigger language plpgsql set search_path = public as $$
begin
    -- service role / SQL editor (no JWT) and realtors are unrestricted
    if auth.uid() is null or public.is_admin() then
        return new;
    end if;
    if new.status <> 'withdrawn'
       or old.status not in ('submitted','under_review','docs_requested')
       or (to_jsonb(new) - 'status' - 'updated_at') is distinct from (to_jsonb(old) - 'status' - 'updated_at')
    then
        raise exception 'clients can only withdraw an open application'
            using errcode = '42501';
    end if;
    return new;
end $$;

drop trigger if exists applications_guard_client_update on public.applications;
create trigger applications_guard_client_update
    before update on public.applications
    for each row execute function public.applications_guard_client_update();

-- 2b. Every new proposta becomes a CRM lead (stage 'offer') in the web admin.
create or replace function public.applications_create_inquiry()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    p   public.client_profiles%rowtype;
    msg text;
begin
    if new.inquiry_id is not null and public.is_admin() then
        return new;  -- realtor linked it to an existing lead explicitly
    end if;
    select * into p from public.client_profiles where user_id = new.user_id;
    msg := format(
        'Proposta #%s via app: %s de R$ %s%s%s%s',
        new.id,
        case new.intent when 'rent' then 'aluguel' else 'compra' end,
        replace(to_char(new.offered_price, 'FM999,999,999,999'), ',', '.'),  -- 8.500 (locale-independent)
        case when new.guarantee_type is not null then ' · garantia: ' || new.guarantee_type else '' end,
        case when new.move_in_date  is not null then ' · mudança: ' || to_char(new.move_in_date, 'DD/MM/YYYY') else '' end,
        case when coalesce(trim(new.message), '') <> '' then E'\n\n' || new.message else '' end
    );
    insert into public.inquiries (name, email, message, property_id, intent, stage)
    values (coalesce(p.full_name, 'Cliente app'), coalesce(p.email, ''), msg, new.listing_id, new.intent, 'offer')
    returning id into new.inquiry_id;
    return new;
end $$;
revoke all on function public.applications_create_inquiry() from public;

drop trigger if exists applications_create_inquiry on public.applications;
create trigger applications_create_inquiry
    before insert on public.applications
    for each row execute function public.applications_create_inquiry();

-- 2c. Keep the linked lead in sync: approved → closed_won; any status change
-- also bumps inquiries.last_activity_at (via 0002's update trigger).
create or replace function public.applications_sync_inquiry()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if new.inquiry_id is not null and new.status is distinct from old.status then
        update public.inquiries
           set stage = case when new.status = 'approved' then 'closed_won' else stage end
         where id = new.inquiry_id;
    end if;
    return null;
end $$;
revoke all on function public.applications_sync_inquiry() from public;

drop trigger if exists applications_sync_inquiry on public.applications;
create trigger applications_sync_inquiry
    after update of status on public.applications
    for each row execute function public.applications_sync_inquiry();

alter table public.applications enable row level security;

drop policy if exists "applications: owner insert" on public.applications;
drop policy if exists "applications: owner select" on public.applications;
drop policy if exists "applications: owner withdraw" on public.applications;
drop policy if exists "applications: admin all" on public.applications;

create policy "applications: owner insert" on public.applications
    for insert to authenticated
    with check (user_id = auth.uid() and status = 'submitted'
                and reviewed_by is null and reviewer_note is null);

create policy "applications: owner select" on public.applications
    for select to authenticated using (user_id = auth.uid());

-- Row-level gate; the guard trigger (2a) blocks every other column change.
create policy "applications: owner withdraw" on public.applications
    for update to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid() and status = 'withdrawn');

create policy "applications: admin all" on public.applications
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── 3. client_documents ──────────────────────────────────────────────

create table if not exists public.client_documents (
    id              bigint generated by default as identity primary key,
    user_id         uuid not null references auth.users(id) on delete cascade,
    application_id  bigint references public.applications(id) on delete set null,
    kind            text not null check (kind in
                        ('rg_cnh','cpf','comprovante_renda','comprovante_residencia',
                         'extrato_bancario','imposto_renda','outro')),
    filename        text not null,
    storage_path    text not null,
    mime_type       text not null,
    size_bytes      bigint not null check (size_bytes > 0),
    created_at      timestamptz not null default now()
);

create index if not exists client_documents_user_idx        on public.client_documents (user_id, created_at desc);
create index if not exists client_documents_application_idx on public.client_documents (application_id);

alter table public.client_documents enable row level security;

drop policy if exists "client_documents: owner select" on public.client_documents;
drop policy if exists "client_documents: owner insert" on public.client_documents;
drop policy if exists "client_documents: owner delete" on public.client_documents;
drop policy if exists "client_documents: admin select" on public.client_documents;

create policy "client_documents: owner select" on public.client_documents
    for select to authenticated using (user_id = auth.uid());

create policy "client_documents: owner insert" on public.client_documents
    for insert to authenticated
    with check (
        user_id = auth.uid()
        and storage_path like auth.uid()::text || '/%'
        and (application_id is null or exists (
            select 1 from public.applications a
            where a.id = application_id and a.user_id = auth.uid()))
    );

create policy "client_documents: owner delete" on public.client_documents
    for delete to authenticated using (user_id = auth.uid());

create policy "client_documents: admin select" on public.client_documents
    for select to authenticated using (public.is_admin());

-- Private bucket; objects live under `<auth.uid()>/<kind>/<ts>-<file>`
-- (see documentPath() in packages/shared/src/api.ts). Downloads use signed URLs.
insert into storage.buckets (id, name, public)
values ('client-documents', 'client-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "client-documents: owner insert" on storage.objects;
drop policy if exists "client-documents: owner select" on storage.objects;
drop policy if exists "client-documents: owner delete" on storage.objects;
drop policy if exists "client-documents: admin select" on storage.objects;

create policy "client-documents: owner insert" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'client-documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "client-documents: owner select" on storage.objects
    for select to authenticated
    using (bucket_id = 'client-documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "client-documents: owner delete" on storage.objects
    for delete to authenticated
    using (bucket_id = 'client-documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "client-documents: admin select" on storage.objects
    for select to authenticated
    using (bucket_id = 'client-documents' and public.is_admin());

-- ─── 4. favorites ─────────────────────────────────────────────────────

create table if not exists public.favorites (
    user_id     uuid not null references auth.users(id) on delete cascade,
    listing_id  bigint not null references public.listings(id) on delete cascade,
    created_at  timestamptz not null default now(),
    primary key (user_id, listing_id)
);

create index if not exists favorites_listing_idx on public.favorites (listing_id);

alter table public.favorites enable row level security;

drop policy if exists "favorites: owner all" on public.favorites;
create policy "favorites: owner all" on public.favorites
    for all to authenticated
    using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ─── 5. Grants (explicit; Supabase's default privileges usually cover this) ──

grant select, insert, update          on public.client_profiles  to authenticated;
grant select, insert, update          on public.applications     to authenticated;
grant select, insert, delete          on public.client_documents to authenticated;
grant select, insert, update, delete  on public.favorites        to authenticated;

-- ─── 6. Realtime (realtor app live-updates on new propostas / leads) ──

do $$
declare t text;
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
        foreach t in array array['applications', 'inquiries'] loop
            if not exists (
                select 1 from pg_publication_tables
                where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
            ) then
                execute format('alter publication supabase_realtime add table public.%I', t);
            end if;
        end loop;
    end if;
end $$;

-- ─── Done. Verify ─────────────────────────────────────────────────────
-- select count(*) from public.client_profiles;     -- expect 0
-- select id, public from storage.buckets where id = 'client-documents';  -- false
-- select tablename from pg_publication_tables where pubname = 'supabase_realtime';


-- ===================== 0013_mobile_client_updates.sql =====================

-- =====================================================================
-- REGLA · 0013 · Mobile client self-service updates
-- Paste into Supabase SQL Editor → Run.  Idempotent.
--
-- 1. Clients can cancel their own visit requests from the app.
-- 2. Clients can link their own uploaded documents to their own proposta
--    (the app uploads during the wizard, before the application exists).
-- =====================================================================

-- ─── 1. Showings: visitor cancels own ─────────────────────────────────
drop policy if exists "showings: visitor cancels own" on public.showings;
create policy "showings: visitor cancels own" on public.showings
    for update to authenticated
    using (created_by = auth.uid() and status in ('scheduled', 'confirmed'))
    with check (created_by = auth.uid() and status = 'cancelled');

-- ─── 2. Client documents: owner links to own application ──────────────
drop policy if exists "client_documents: owner update" on public.client_documents;
create policy "client_documents: owner update" on public.client_documents
    for update to authenticated
    using (user_id = auth.uid())
    with check (
        user_id = auth.uid()
        and storage_path like auth.uid()::text || '/%'
        and (application_id is null or exists (
            select 1 from public.applications a
            where a.id = application_id and a.user_id = auth.uid()))
    );

grant update on public.client_documents to authenticated;


-- ===================== 0014_proposal_negotiation.sql =====================

-- =====================================================================
-- REGLA · 0014 · QuintoAndar-style proposal lifecycle
-- Paste into Supabase SQL Editor → Run.  Idempotent.
--
--   client sends proposta (cadastro + CPF + renda + terms, NO documents)
--     → negotiation: each side may accept / counter / decline; whoever did
--       NOT make the latest offer must act (`awaiting`)
--     → accepted (agreed_price locked) → client uploads documents
--     → docs_review → realtor approves (lead closed_won) or asks for
--       corrections (docs_requested → client re-sends → docs_review)
--
-- Clients act only through the security-definer RPCs below; their direct
-- UPDATE stays limited to withdrawing (0012 guard trigger).
-- =====================================================================

-- ─── 1. applications: new statuses + negotiation columns ──────────────
alter table public.applications drop constraint if exists applications_status_check;
alter table public.applications add constraint applications_status_check check (status in (
    'submitted', 'under_review', 'negotiating', 'accepted',
    'docs_review', 'docs_requested', 'approved', 'rejected', 'withdrawn'));

alter table public.applications add column if not exists agreed_price bigint
    check (agreed_price is null or agreed_price > 0);
alter table public.applications add column if not exists awaiting text
    check (awaiting is null or awaiting in ('client', 'realtor'));

create index if not exists applications_awaiting_idx on public.applications (awaiting, updated_at desc)
    where awaiting is not null;

-- Whose turn a status implies. 'negotiating' is decided by the latest offer.
create or replace function public.proposal_awaiting_for(p_status text)
returns text language sql immutable as $$
    select case
        when p_status in ('submitted', 'under_review', 'docs_review') then 'realtor'
        when p_status in ('accepted', 'docs_requested')                then 'client'
        else null
    end
$$;

update public.applications
   set awaiting = public.proposal_awaiting_for(status)
 where status <> 'negotiating' and awaiting is distinct from public.proposal_awaiting_for(status);

create or replace function public.applications_set_awaiting()
returns trigger language plpgsql set search_path = public as $$
begin
    if tg_op = 'INSERT' then
        new.awaiting := coalesce(public.proposal_awaiting_for(new.status), 'realtor');
    elsif new.status is distinct from old.status and new.status <> 'negotiating' then
        new.awaiting := public.proposal_awaiting_for(new.status);
    end if;
    return new;
end $$;

drop trigger if exists applications_set_awaiting on public.applications;
create trigger applications_set_awaiting
    before insert or update on public.applications
    for each row execute function public.applications_set_awaiting();

-- The 0012 guard lets clients only withdraw. Calls made from inside the
-- security-definer RPCs below run as the function owner, not `authenticated`.
create or replace function public.applications_guard_client_update()
returns trigger language plpgsql set search_path = public as $$
begin
    if auth.uid() is null or public.is_admin() or current_user <> 'authenticated' then
        return new;
    end if;
    if new.status <> 'withdrawn'
       or old.status not in ('submitted', 'under_review', 'negotiating', 'accepted', 'docs_review', 'docs_requested')
       or (to_jsonb(new) - 'status' - 'updated_at' - 'awaiting') is distinct from (to_jsonb(old) - 'status' - 'updated_at' - 'awaiting')
    then
        raise exception 'clients can only withdraw an open application'
            using errcode = '42501';
    end if;
    return new;
end $$;

-- ─── 2. application_offers: the negotiation timeline ──────────────────
create table if not exists public.application_offers (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references public.applications(id) on delete cascade,
    author          text not null check (author in ('client', 'realtor')),
    author_id       uuid references auth.users(id) on delete set null,
    price           bigint not null check (price > 0),
    guarantee_type  text check (guarantee_type in
                        ('seguro_fianca','fiador','caucao','titulo_capitalizacao','sem_garantia')),
    move_in_date    date,
    message         text,
    created_at      timestamptz not null default now()
);

create index if not exists application_offers_app_idx on public.application_offers (application_id, created_at);
create index if not exists application_offers_author_idx on public.application_offers (author_id);

alter table public.application_offers enable row level security;

drop policy if exists "application_offers: owner select" on public.application_offers;
drop policy if exists "application_offers: admin all" on public.application_offers;

create policy "application_offers: owner select" on public.application_offers
    for select to authenticated
    using (exists (select 1 from public.applications a
                   where a.id = application_id and a.user_id = auth.uid()));

create policy "application_offers: admin all" on public.application_offers
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant select on public.application_offers to authenticated;

-- First offer = the proposta itself.
create or replace function public.applications_initial_offer()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.application_offers
        (application_id, author, author_id, price, guarantee_type, move_in_date, message)
    values (new.id, 'client', new.user_id, new.offered_price, new.guarantee_type, new.move_in_date, new.message);
    return null;
end $$;
revoke all on function public.applications_initial_offer() from public;

drop trigger if exists applications_initial_offer on public.applications;
create trigger applications_initial_offer
    after insert on public.applications
    for each row execute function public.applications_initial_offer();

-- Backfill: proposals created before 0014 get their opening offer.
insert into public.application_offers (application_id, author, author_id, price, guarantee_type, move_in_date, message, created_at)
select a.id, 'client', a.user_id, a.offered_price, a.guarantee_type, a.move_in_date, a.message, a.created_at
from public.applications a
where not exists (select 1 from public.application_offers o where o.application_id = a.id);

-- ─── 3. RPCs ──────────────────────────────────────────────────────────

-- Locks the application row and returns it with the caller's party
-- ('client' / 'realtor'). Raises 42501 unless the caller is the realtor or
-- the owning client.
create or replace function public.proposal_party(p_app public.applications)
returns text language plpgsql stable security definer set search_path = public as $$
begin
    if auth.uid() is null then
        raise exception 'not authenticated' using errcode = '42501';
    end if;
    if public.is_admin() then
        return 'realtor';
    elsif p_app.user_id = auth.uid() then
        return 'client';
    end if;
    raise exception 'not your application' using errcode = '42501';
end $$;
revoke all on function public.proposal_party(public.applications) from public;

-- Counter-offer: new terms from whoever's turn it is. Missing optional
-- terms are inherited from the latest offer.
create or replace function public.proposal_counter(
    p_application_id bigint,
    p_price          bigint,
    p_message        text default null,
    p_guarantee_type text default null,
    p_move_in_date   date default null)
returns public.application_offers
language plpgsql security definer set search_path = public as $$
declare
    app   public.applications;
    party text;
    last  public.application_offers;
    offer public.application_offers;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if app.status not in ('submitted', 'under_review', 'negotiating') or app.awaiting is distinct from party then
        raise exception 'it is not your turn to counter' using errcode = '42501';
    end if;
    if p_price is null or p_price <= 0 then
        raise exception 'price must be positive' using errcode = '22023';
    end if;

    select * into last from public.application_offers
     where application_id = p_application_id order by created_at desc, id desc limit 1;

    insert into public.application_offers (application_id, author, author_id, price, guarantee_type, move_in_date, message)
    values (p_application_id, party, auth.uid(), p_price,
            coalesce(p_guarantee_type, last.guarantee_type),
            coalesce(p_move_in_date, last.move_in_date),
            nullif(trim(p_message), ''))
    returning * into offer;

    update public.applications
       set status = 'negotiating',
           awaiting = case party when 'client' then 'realtor' else 'client' end
     where id = p_application_id;
    return offer;
end $$;

-- Accept the latest offer (must be the other party's).
create or replace function public.proposal_accept(p_application_id bigint)
returns public.applications
language plpgsql security definer set search_path = public as $$
declare
    app  public.applications;
    party text;
    last public.application_offers;
    res  public.applications;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if app.status not in ('submitted', 'under_review', 'negotiating') or app.awaiting is distinct from party then
        raise exception 'it is not your turn to accept' using errcode = '42501';
    end if;
    select * into last from public.application_offers
     where application_id = p_application_id order by created_at desc, id desc limit 1;
    if last.author = party then
        raise exception 'cannot accept your own offer' using errcode = '42501';
    end if;

    update public.applications
       set status = 'accepted',
           agreed_price = last.price,
           guarantee_type = coalesce(last.guarantee_type, guarantee_type),
           move_in_date = coalesce(last.move_in_date, move_in_date),
           reviewed_by = case when party = 'realtor' then auth.uid() else reviewed_by end
     where id = p_application_id
    returning * into res;
    return res;
end $$;

-- Decline: realtor → rejected (with note), client → withdrawn.
create or replace function public.proposal_decline(p_application_id bigint, p_note text default null)
returns public.applications
language plpgsql security definer set search_path = public as $$
declare
    app public.applications;
    party text;
    res public.applications;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if app.status in ('approved', 'rejected', 'withdrawn') then
        raise exception 'application is already closed' using errcode = '42501';
    end if;
    if party = 'realtor' then
        update public.applications
           set status = 'rejected', reviewer_note = nullif(trim(p_note), ''), reviewed_by = auth.uid()
         where id = p_application_id
        returning * into res;
    else
        update public.applications set status = 'withdrawn'
         where id = p_application_id
        returning * into res;
    end if;
    return res;
end $$;

-- Client finished uploading documents → realtor reviews them.
create or replace function public.proposal_docs_sent(p_application_id bigint)
returns public.applications
language plpgsql security definer set search_path = public as $$
declare
    app public.applications;
    party text;
    res public.applications;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if party <> 'client' or app.status not in ('accepted', 'docs_requested') then
        raise exception 'documents can only be sent after acceptance' using errcode = '42501';
    end if;
    update public.applications set status = 'docs_review'
     where id = p_application_id
    returning * into res;
    return res;
end $$;

revoke all on function public.proposal_counter(bigint, bigint, text, text, date) from public;
revoke all on function public.proposal_accept(bigint) from public;
revoke all on function public.proposal_decline(bigint, text) from public;
revoke all on function public.proposal_docs_sent(bigint) from public;
grant execute on function public.proposal_counter(bigint, bigint, text, text, date) to authenticated;
grant execute on function public.proposal_accept(bigint) to authenticated;
grant execute on function public.proposal_decline(bigint, text) to authenticated;
grant execute on function public.proposal_docs_sent(bigint) to authenticated;

-- ─── 4. Realtime: offers stream to both apps ──────────────────────────
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (select 1 from pg_publication_tables
                       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'application_offers')
    then
        alter publication supabase_realtime add table public.application_offers;
    end if;
end $$;
