package br.com.imoveisregla.core.data.supabase

import br.com.imoveisregla.core.model.ApplicationInput
import br.com.imoveisregla.core.model.ApplicationIntent
import br.com.imoveisregla.core.model.ApplicationStatus
import br.com.imoveisregla.core.model.ClientDocument
import br.com.imoveisregla.core.model.ClientProfileInput
import br.com.imoveisregla.core.model.DocumentKind
import br.com.imoveisregla.core.model.EmploymentType
import br.com.imoveisregla.core.model.GuaranteeType
import br.com.imoveisregla.core.model.ListingStatus
import br.com.imoveisregla.core.model.ShowingStatus
import br.com.imoveisregla.core.model.ShowingType
import br.com.imoveisregla.core.model.VisitInput
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// Insert / update payloads (snake_case). Never carry id / created_at / updated_at —
// those are generated by Postgres.

internal fun String?.blankToNull(): String? = this?.trim()?.takeIf { it.isNotEmpty() }

@Serializable
internal data class ProfileUpsert(
    @SerialName("user_id") val userId: String,
    @SerialName("full_name") val fullName: String,
    val email: String,
    val phone: String,
    val cpf: String?,
    @SerialName("birth_date") val birthDate: String?,
    val occupation: String?,
    @SerialName("employment_type") val employmentType: EmploymentType?,
    @SerialName("monthly_income") val monthlyIncome: Long?,
    val residents: Int,
    @SerialName("has_pets") val hasPets: Boolean,
) {
    companion object {
        fun from(userId: String, i: ClientProfileInput) = ProfileUpsert(
            userId = userId,
            fullName = i.fullName.trim(),
            email = i.email.trim(),
            phone = i.phone.trim(),
            cpf = i.cpf.blankToNull(),
            birthDate = i.birthDate.blankToNull(),
            occupation = i.occupation.blankToNull(),
            employmentType = i.employmentType,
            monthlyIncome = i.monthlyIncome,
            residents = i.residents,
            hasPets = i.hasPets,
        )
    }
}

@Serializable
internal data class ApplicationInsert(
    @SerialName("listing_id") val listingId: Long,
    @SerialName("user_id") val userId: String,
    val intent: ApplicationIntent,
    @SerialName("offered_price") val offeredPrice: Long,
    @SerialName("guarantee_type") val guaranteeType: GuaranteeType?,
    @SerialName("move_in_date") val moveInDate: String?,
    val message: String?,
) {
    companion object {
        fun from(userId: String, i: ApplicationInput) = ApplicationInsert(
            listingId = i.listingId,
            userId = userId,
            intent = i.intent,
            offeredPrice = i.offeredPrice,
            guaranteeType = i.guaranteeType,
            moveInDate = i.moveInDate.blankToNull(),
            message = i.message.blankToNull(),
        )
    }
}

@Serializable
internal data class ApplicationReviewPatch(
    val status: ApplicationStatus,
    @SerialName("reviewer_note") val reviewerNote: String?,
    @SerialName("reviewed_by") val reviewedBy: String,
)

@Serializable
internal data class ApplicationStatusPatch(val status: ApplicationStatus)

@Serializable
internal data class DocumentApplicationPatch(@SerialName("application_id") val applicationId: Long)

@Serializable
internal data class ListingStatusPatch(val status: ListingStatus)

@Serializable
internal data class ShowingStatusPatch(val status: ShowingStatus)

@Serializable
internal data class DocumentInsert(
    @SerialName("user_id") val userId: String,
    @SerialName("application_id") val applicationId: Long?,
    val kind: DocumentKind,
    val filename: String,
    @SerialName("storage_path") val storagePath: String,
    @SerialName("mime_type") val mimeType: String,
    @SerialName("size_bytes") val sizeBytes: Long,
) {
    companion object {
        fun copyOf(d: ClientDocument, applicationId: Long?) = DocumentInsert(
            userId = d.userId, applicationId = applicationId, kind = d.kind, filename = d.filename,
            storagePath = d.storagePath, mimeType = d.mimeType, sizeBytes = d.sizeBytes,
        )
    }
}

@Serializable
internal data class ShowingInsert(
    @SerialName("listing_id") val listingId: Long,
    val type: ShowingType,
    val status: ShowingStatus,
    @SerialName("starts_at") val startsAt: String,
    @SerialName("visitor_name") val visitorName: String,
    @SerialName("visitor_email") val visitorEmail: String,
    @SerialName("visitor_phone") val visitorPhone: String?,
    val notes: String?,
    @SerialName("created_by") val createdBy: String,
) {
    companion object {
        fun from(userId: String, v: VisitInput) = ShowingInsert(
            listingId = v.listingId,
            type = ShowingType.PRIVATE,
            status = ShowingStatus.SCHEDULED,
            startsAt = v.startsAt,
            visitorName = v.visitorName.trim(),
            visitorEmail = v.visitorEmail.trim(),
            visitorPhone = v.visitorPhone.blankToNull(),
            notes = v.notes.blankToNull(),
            createdBy = userId,
        )
    }
}

@Serializable
internal data class FavoriteInsert(
    @SerialName("user_id") val userId: String,
    @SerialName("listing_id") val listingId: Long,
)

@Serializable
internal data class FavoriteRow(@SerialName("listing_id") val listingId: Long)

@Serializable
internal data class NoteInsert(
    @SerialName("inquiry_id") val inquiryId: Long,
    val body: String,
    @SerialName("author_id") val authorId: String,
)

@Serializable
internal data class IdRow(val id: Long)
