-- =====================================================================
-- REGLA · Supabase init
-- Paste this entire file into Supabase Dashboard → SQL Editor → Run.
-- Idempotent (safe to re-run; uses if-not-exists / on-conflict).
-- =====================================================================

-- ─── Tables ──────────────────────────────────────────────────────────

create table if not exists public.listings (
    id              bigint generated by default as identity primary key,
    slug            text unique not null,
    title           text not null,
    city            text not null,
    country         text not null,
    neighborhood    text not null,
    type            text not null check (type in ('apartment','house','commercial','land')),
    price           bigint not null check (price >= 0),
    currency        text not null check (currency in ('USD','EUR','GBP','BRL')),
    beds            smallint not null default 0,
    baths           smallint not null default 0,
    area_m2         integer not null check (area_m2 > 0),
    area_ft2        integer,
    tags            text[] not null default '{}',
    palette         text not null default 'navy',
    shape           text not null default 'apartment',
    summary         text not null,
    description     text not null,
    status          text not null default 'draft' check (status in ('draft','live','sold','withdrawn')),
    featured        boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    created_by      uuid references auth.users(id)
);

create index if not exists listings_status_created_idx on public.listings (status, created_at desc);
create index if not exists listings_city_idx           on public.listings (city);
create index if not exists listings_type_idx           on public.listings (type);
create index if not exists listings_featured_idx       on public.listings (featured) where featured = true;

create table if not exists public.listing_photos (
    id              bigint generated by default as identity primary key,
    listing_id      bigint not null references public.listings(id) on delete cascade,
    storage_path    text not null,
    alt_text        text,
    position        smallint not null default 0,
    created_at      timestamptz not null default now()
);

create index if not exists listing_photos_listing_idx on public.listing_photos (listing_id, position);

create table if not exists public.inquiries (
    id              bigint generated by default as identity primary key,
    name            text not null,
    email           text not null,
    intent          text,
    region          text,
    message         text not null,
    property_id     bigint references public.listings(id) on delete set null,
    read            boolean not null default false,
    created_at      timestamptz not null default now()
);

create index if not exists inquiries_created_idx on public.inquiries (created_at desc);
create index if not exists inquiries_unread_idx  on public.inquiries (read) where read = false;

-- ─── updated_at trigger ──────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end $$;

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
    before update on public.listings
    for each row execute function public.set_updated_at();

-- ─── Row Level Security ──────────────────────────────────────────────

alter table public.listings        enable row level security;
alter table public.listing_photos  enable row level security;
alter table public.inquiries       enable row level security;

-- Listings: anyone can SELECT live; authenticated users can do everything.
drop policy if exists "listings: public reads live"    on public.listings;
drop policy if exists "listings: auth reads all"       on public.listings;
drop policy if exists "listings: auth writes"          on public.listings;

create policy "listings: public reads live" on public.listings
    for select using (status = 'live');

create policy "listings: auth reads all" on public.listings
    for select to authenticated using (true);

create policy "listings: auth writes" on public.listings
    for all to authenticated using (true) with check (true);

-- Photos: anyone can SELECT; authenticated can manage.
drop policy if exists "photos: public reads"  on public.listing_photos;
drop policy if exists "photos: auth writes"   on public.listing_photos;

create policy "photos: public reads" on public.listing_photos
    for select using (true);

create policy "photos: auth writes" on public.listing_photos
    for all to authenticated using (true) with check (true);

-- Inquiries: anyone can INSERT (public form); authenticated can manage.
drop policy if exists "inquiries: public inserts" on public.inquiries;
drop policy if exists "inquiries: auth manage"    on public.inquiries;

create policy "inquiries: public inserts" on public.inquiries
    for insert with check (true);

create policy "inquiries: auth manage" on public.inquiries
    for all to authenticated using (true) with check (true);

-- ─── Storage bucket for listing photos ───────────────────────────────

insert into storage.buckets (id, name, public)
values ('listing-photos', 'listing-photos', true)
on conflict (id) do nothing;

drop policy if exists "listing-photos: public read"   on storage.objects;
drop policy if exists "listing-photos: auth manage"   on storage.objects;

create policy "listing-photos: public read" on storage.objects
    for select using (bucket_id = 'listing-photos');

create policy "listing-photos: auth manage" on storage.objects
    for all to authenticated
    using (bucket_id = 'listing-photos')
    with check (bucket_id = 'listing-photos');

-- ─── Seed: 20 listings (matches src/lib/listings.ts) ─────────────────

insert into public.listings
    (id, slug, title, city, country, neighborhood, type, price, currency, beds, baths, area_m2, area_ft2, tags, palette, shape, summary, description, status, featured)
values
    (1,  'glass-walled-studio-itaim',     'Glass-Walled Studio in Itaim',     'São Paulo', 'Brazil',          'Itaim Bibi',     'apartment',  1850000,  'BRL', 1, 1, 62,    null,  array['New'],                'sunset',     'apartment',  'A 12th-floor studio with double-height windows facing the financial district skyline.', 'A 12th-floor studio in a 2022 tower, with double-height curtain-wall windows facing the Faria Lima skyline. Polished concrete floors, Vola fittings throughout, full furnishings included. Building amenities: 25-metre lap pool, gym, two reserved parking bays.', 'live', false),
    (2,  'townhouse-vila-madalena',       'Townhouse in Vila Madalena',       'São Paulo', 'Brazil',          'Vila Madalena',  'house',      4200000,  'BRL', 4, 3, 320,   null,  array['Featured'],           'forest',     'townhouse',  'Mid-century townhouse with internal courtyard and restored mosaic floors.', 'A 1958 townhouse by a student of Vilanova Artigas, fully restored in 2023. Internal courtyard, original cobogó breeze blocks, restored mosaic floors. Off-street parking for two. Walk to Praça Pôr-do-Sol.', 'live', true),
    (3,  'paulista-office-floor',         'Avenida Paulista Office Floor',    'São Paulo', 'Brazil',          'Bela Vista',     'commercial', 12000000, 'BRL', 0, 4, 880,   null,  array['Investment'],         'navy',       'tower',      'Full-floor commercial office, currently leased to a multinational law firm.', 'Full-floor commercial office in a Triple-A Paulista tower. Raised access floors, fan-coil HVAC, 12 reserved parking bays. Leased to a multinational law firm with 5 years remaining at current passing rent of R$ 720k/year.', 'live', false),
    (4,  'penthouse-river-views',         'Penthouse with River Views',       'Lisbon',    'Portugal',        'Príncipe Real',  'apartment',  2400000,  'EUR', 3, 3, 245,   null,  array['Featured','New'],     'ocean',      'apartment',  'Duplex penthouse with two private terraces and Tagus views.', 'A duplex penthouse with two private terraces totalling 110 m², direct views to the Tagus and 25 de Abril bridge. Restored 1930s tilework throughout the social rooms, full smart-home retrofit, two parking spaces.', 'live', true),
    (5,  'pombaline-townhouse-chiado',    'Pombaline Townhouse, Chiado',      'Lisbon',    'Portugal',        'Chiado',         'house',      3650000,  'EUR', 5, 4, 410,   null,  array['Heritage'],           'terracotta', 'townhouse',  'Four-storey Pombaline townhouse with internal lift and courtyard.', 'A 1758 four-storey Pombaline townhouse, fully restored 2022. Internal lift, original carpentry and stonework, south-facing internal courtyard. Listed Grade II — restoration brief on file.', 'live', false),
    (6,  'vineyard-estate-alentejo',      'Vineyard Estate, Alentejo',        'Lisbon',    'Portugal',        'Alentejo',       'land',       5200000,  'EUR', 0, 0, 120000, null, array['Land','Investment'],  'olive',      'land',       '12 hectares of producing vineyard, 90 minutes from Lisbon.', '12 hectares of producing vineyard with restored stone outbuilding, 90 minutes from Lisbon. Sale includes the operating winery, the existing label, and three years of bottled stock at the bodega.', 'live', false),
    (7,  'bayfront-tower-residence',      'Bayfront Tower Residence',         'Miami',     'United States',   'Brickell',       'apartment',  3850000,  'USD', 3, 4, 235,   2530, array['Featured'],           'cyan',       'tower',      'Three-bedroom corner unit on the 38th floor with 270° bay views.', 'A three-bedroom corner unit on the 38th floor of an Arquitectonica tower, with 270° views over Biscayne Bay and the Brickell skyline. Private elevator vestibule, full building amenities, two valet parking bays.', 'live', true),
    (8,  'coral-gables-villa',            'Coral Gables Villa',               'Miami',     'United States',   'Coral Gables',   'house',      6800000,  'USD', 6, 7, 720,   7750, array['New'],                'sand',       'villa',      'Mediterranean-revival villa, 1928, fully renovated 2024.', 'A Mediterranean-revival villa, 1928, fully renovated 2024 by a Pritzker-laureate-trained office. Pool, guest house, two-car garage, walled garden. Walking distance to Miracle Mile.', 'live', false),
    (9,  'wynwood-loft',                  'Wynwood Loft',                     'Miami',     'United States',   'Wynwood',        'apartment',  1450000,  'USD', 2, 2, 140,   1505, array[]::text[],             'plum',       'loft',       'Industrial loft conversion in the arts district.', 'Industrial loft conversion in the heart of the arts district. Polished concrete, exposed timber beams, gallery-grade hanging system pre-installed. Two reserved parking spaces, secure freight elevator.', 'live', false),
    (10, 'mayfair-mews-house',            'Mayfair Mews House',               'London',    'United Kingdom',  'Mayfair',        'house',      8200000,  'GBP', 4, 4, 290,   null,  array['Featured','Heritage'],'wine',       'townhouse',  'Two-storey mews house off Park Lane, fully refurbished.', 'A two-storey mews house steps off Park Lane, fully refurbished 2024. Roof terrace with Hyde Park views, private garage, lift to all floors. Freehold.', 'live', true),
    (11, 'borough-market-apartment',      'Borough Market Apartment',         'London',    'United Kingdom',  'Borough',        'apartment',  1950000,  'GBP', 2, 2, 118,   null,  array['New'],                'graphite',   'apartment',  'Converted warehouse loft a block from Borough Market.', 'A converted warehouse loft a block from Borough Market. Crittall-style steel windows, original brickwork, polished concrete floors, private secure parking.', 'live', false),
    (12, 'shoreditch-office',             'Shoreditch Office Building',       'London',    'United Kingdom',  'Shoreditch',     'commercial', 14500000, 'GBP', 0, 6, 1820,  null,  array['Investment'],         'slate',      'commercial', 'Five-storey commercial building, fully tenanted under a 10-year FRI lease.', 'Five-storey commercial building, fully tenanted to a creative agency under a 10-year FRI lease. Current passing rent £680,000 p.a., breaks unconditional. Freehold.', 'live', false),
    (13, 'salamanca-apartment',           'Salamanca Apartment',              'Madrid',    'Spain',           'Salamanca',      'apartment',  2100000,  'EUR', 3, 3, 185,   null,  array['Featured'],           'amber',      'apartment',  'Belle-époque flat in Madrid''s most coveted barrio.', 'A belle-époque apartment in Madrid''s most coveted barrio. 4-metre ceilings, restored hydraulic-tile floors, two interior patios, full structural survey on file.', 'live', true),
    (14, 'chamberi-townhouse',            'Chamberí Townhouse',               'Madrid',    'Spain',           'Chamberí',       'house',      3400000,  'EUR', 5, 4, 340,   null,  array[]::text[],             'rose',       'townhouse',  '19th-century three-storey casa palacio with private garage.', 'A 19th-century three-storey casa palacio, fully renovated. South-facing roof terrace, private garage, fully restored carpentry and ironwork.', 'live', false),
    (15, 'toledo-estate',                 'Toledo Estate',                    'Madrid',    'Spain',           'Toledo Province','land',       4800000,  'EUR', 0, 0, 450000, null, array['Land'],               'olive',      'land',       '45 hectares of olive grove with 18th-century farmhouse.', '45 hectares of producing olive grove with restored 18th-century farmhouse, 50 minutes from central Madrid by motorway. Existing AOC label, 2,000 trees in production.', 'live', false),
    (16, 'palm-jumeirah-villa',           'Palm Jumeirah Villa',              'Dubai',     'United Arab Emirates','Palm Jumeirah','house',    14500000, 'USD', 7, 9, 950,   10220, array['Featured','New'],     'gold',       'villa',      'Signature villa on a frond of the Palm with private beach.', 'A signature villa on a frond of the Palm with private beach, infinity pool, separate staff quarters, and direct views to Atlantis. Five guest suites, a principal suite spanning the upper floor, garaging for four.', 'live', true),
    (17, 'downtown-penthouse',            'Downtown Penthouse',               'Dubai',     'United Arab Emirates','Downtown',   'apartment',  5200000,  'USD', 4, 5, 410,   null,  array[]::text[],             'amber',      'tower',      'Full-floor penthouse opposite Burj Khalifa.', 'A full-floor penthouse opposite Burj Khalifa with 270° views, private pool deck, two parking bays. Hand-over standard with all bespoke joinery and stonework completed.', 'live', false),
    (18, 'orchard-condominium',           'Orchard Road Condominium',         'Singapore', 'Singapore',       'Orchard',        'apartment',  4800000,  'USD', 3, 3, 220,   null,  array['Featured'],           'cyan',       'tower',      'Three-bedroom condominium one block from Orchard.', 'A three-bedroom condominium in a long-let freehold tower one block from Orchard. Pool, gym, 24-hour concierge. Two-bay parking included.', 'live', true),
    (19, 'bukit-timah-house',             'Bukit Timah House',                'Singapore', 'Singapore',       'Bukit Timah',    'house',      11500000, 'USD', 5, 6, 620,   null,  array['Heritage'],           'forest',     'villa',      'Black-and-white colonial bungalow on a 1,200 m² freehold plot.', 'A black-and-white colonial bungalow on a 1,200 m² freehold plot, fully restored 2023. Internal lift, swimming pool, separate staff annex, mature garden.', 'live', false),
    (20, 'marina-bay-office',             'Marina Bay Office Tower',          'Singapore', 'Singapore',       'Marina Bay',     'commercial', 32000000, 'USD', 0, 12, 4800, null,  array['Investment'],         'navy',       'commercial', 'Strata-titled prime office floor in a Marina Bay landmark.', 'A strata-titled prime office floor in a Marina Bay landmark, fully leased to a sovereign-wealth tenant, 8.5 years remaining on the headlease. Reversionary upside on rent review.', 'live', false)
on conflict (slug) do nothing;

-- Bump the identity sequence past the seed IDs so new inserts start at 21.
select setval(pg_get_serial_sequence('public.listings', 'id'), 20);

-- ─── Done. Verify ───────────────────────────────────────────────────
-- Run: select count(*) from public.listings;     -- expect: 20
-- Run: select count(*) from public.inquiries;    -- expect: 0
-- Run: select id from storage.buckets;           -- expect listing-photos in the list
