-- =====================================================================
-- REGLA · Slice 2.1 · CRM pipeline + notes
-- Paste into Supabase Dashboard → SQL Editor → Run.
-- Idempotent — safe to re-run.
-- =====================================================================

-- ─── Stage + priority on inquiries ────────────────────────────────────

alter table public.inquiries
    add column if not exists stage text not null default 'inbox'
        check (stage in ('inbox', 'qualified', 'showing', 'offer', 'closed_won', 'closed_lost'));

alter table public.inquiries
    add column if not exists priority text not null default 'medium'
        check (priority in ('low', 'medium', 'high'));

alter table public.inquiries
    add column if not exists last_activity_at timestamptz not null default now();

-- Trigger: bump last_activity_at on every inquiry update
create or replace function public.set_inquiry_activity()
returns trigger language plpgsql as $$
begin
    new.last_activity_at = now();
    return new;
end $$;

drop trigger if exists inquiries_set_activity on public.inquiries;
create trigger inquiries_set_activity
    before update on public.inquiries
    for each row execute function public.set_inquiry_activity();

create index if not exists inquiries_stage_idx on public.inquiries (stage, last_activity_at desc);
create index if not exists inquiries_priority_idx on public.inquiries (priority, last_activity_at desc) where priority <> 'medium';

-- ─── Lead notes timeline ──────────────────────────────────────────────

create table if not exists public.lead_notes (
    id          bigint generated by default as identity primary key,
    inquiry_id  bigint not null references public.inquiries(id) on delete cascade,
    body        text not null,
    author_id   uuid references auth.users(id),
    created_at  timestamptz not null default now()
);

create index if not exists lead_notes_inquiry_idx on public.lead_notes (inquiry_id, created_at desc);

alter table public.lead_notes enable row level security;

drop policy if exists "lead_notes: auth manage" on public.lead_notes;
create policy "lead_notes: auth manage" on public.lead_notes
    for all to authenticated using (true) with check (true);

-- ─── Backfill: any existing inquiries get stage='inbox', priority='medium'
-- (default columns already handled this; the next two lines are no-ops the first time
-- through but make re-running safe.)

update public.inquiries set stage = coalesce(stage, 'inbox') where stage is null;
update public.inquiries set priority = coalesce(priority, 'medium') where priority is null;

-- ─── Done. Verify ────────────────────────────────────────────────────
-- Run: select stage, count(*) from public.inquiries group by stage;
-- Run: select count(*) from public.lead_notes;     -- expect 0 initially
