-- =====================================================================
-- REGLA · Slice 2.2 · Showings + open-house RSVPs
-- Paste into Supabase SQL Editor → Run.  Idempotent.
-- =====================================================================

-- ─── Showings (private viewings + open houses) ─────────────────────────
create table if not exists public.showings (
    id                bigint generated by default as identity primary key,
    listing_id        bigint not null references public.listings(id) on delete cascade,
    inquiry_id        bigint references public.inquiries(id) on delete set null,
    type              text not null default 'private'
                          check (type in ('private', 'open_house')),
    starts_at         timestamptz not null,
    duration_minutes  smallint not null default 30 check (duration_minutes between 5 and 600),
    status            text not null default 'scheduled'
                          check (status in ('scheduled','confirmed','attended','no_show','cancelled')),
    visitor_name      text,
    visitor_email     text,
    visitor_phone     text,
    notes             text,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now(),
    created_by        uuid references auth.users(id)
);

create index if not exists showings_starts_idx        on public.showings (starts_at desc);
create index if not exists showings_listing_starts    on public.showings (listing_id, starts_at);
create index if not exists showings_inquiry_idx       on public.showings (inquiry_id);
create index if not exists showings_open_active_idx   on public.showings (starts_at)
    where type = 'open_house' and status in ('scheduled','confirmed');

drop trigger if exists showings_set_updated_at on public.showings;
create trigger showings_set_updated_at
    before update on public.showings
    for each row execute function public.set_updated_at();

-- ─── RSVPs for open houses ─────────────────────────────────────────────
create table if not exists public.showing_rsvps (
    id          bigint generated by default as identity primary key,
    showing_id  bigint not null references public.showings(id) on delete cascade,
    name        text not null,
    email       text not null,
    phone       text,
    party_size  smallint not null default 1 check (party_size between 1 and 20),
    message     text,
    created_at  timestamptz not null default now()
);

create index if not exists showing_rsvps_showing_idx on public.showing_rsvps (showing_id, created_at desc);

-- ─── RLS ───────────────────────────────────────────────────────────────
alter table public.showings       enable row level security;
alter table public.showing_rsvps  enable row level security;

drop policy if exists "showings: public reads open"  on public.showings;
drop policy if exists "showings: auth manage"        on public.showings;

create policy "showings: public reads open" on public.showings
    for select using (type = 'open_house' and status in ('scheduled','confirmed'));

create policy "showings: auth manage" on public.showings
    for all to authenticated using (true) with check (true);

drop policy if exists "rsvps: public insert"  on public.showing_rsvps;
drop policy if exists "rsvps: auth manage"    on public.showing_rsvps;

create policy "rsvps: public insert" on public.showing_rsvps
    for insert with check (true);

create policy "rsvps: auth manage" on public.showing_rsvps
    for all to authenticated using (true) with check (true);

-- ─── Done. Verify ──────────────────────────────────────────────────────
-- select count(*) from public.showings;       -- expect 0
-- select count(*) from public.showing_rsvps;  -- expect 0
