-- =====================================================================
-- REGLA · Slice 2.4 — Agents foundation
-- Paste into Supabase Dashboard → SQL Editor → Run.
-- Idempotent.
-- =====================================================================

create table if not exists public.agents (
    id              bigint generated by default as identity primary key,
    slug            text unique not null,
    name            text not null,
    email           text unique not null,
    phone           text,
    photo_path      text,
    bio             text not null default '',
    headline        text,
    role            text not null default 'agent' check (role in ('principal','partner','agent','associate')),
    creci           text,
    city            text,
    country         text,
    languages       text[] not null default '{}',
    specialties     text[] not null default '{}',
    active          boolean not null default true,
    user_id         uuid references auth.users(id) on delete set null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    created_by      uuid references auth.users(id)
);

create index if not exists agents_active_idx on public.agents (active) where active = true;
create index if not exists agents_role_idx   on public.agents (role);
create index if not exists agents_city_idx   on public.agents (city);

drop trigger if exists agents_set_updated_at on public.agents;
create trigger agents_set_updated_at
    before update on public.agents
    for each row execute function public.set_updated_at();

-- Listings ↔ agents (optional FK, nullable)
alter table public.listings
    add column if not exists agent_id bigint references public.agents(id) on delete set null;
create index if not exists listings_agent_idx on public.listings (agent_id);

-- ─── RLS ─────────────────────────────────────────────────────────────

alter table public.agents enable row level security;

drop policy if exists "agents: public reads active" on public.agents;
drop policy if exists "agents: auth reads all"      on public.agents;
drop policy if exists "agents: auth writes"         on public.agents;

create policy "agents: public reads active" on public.agents
    for select using (active = true);

create policy "agents: auth reads all" on public.agents
    for select to authenticated using (true);

create policy "agents: auth writes" on public.agents
    for all to authenticated using (true) with check (true);

-- ─── Storage bucket for agent photos ─────────────────────────────────

insert into storage.buckets (id, name, public)
values ('agent-photos', 'agent-photos', true)
on conflict (id) do nothing;

drop policy if exists "agent-photos: public read" on storage.objects;
drop policy if exists "agent-photos: auth manage" on storage.objects;

create policy "agent-photos: public read" on storage.objects
    for select using (bucket_id = 'agent-photos');

create policy "agent-photos: auth manage" on storage.objects
    for all to authenticated
    using (bucket_id = 'agent-photos')
    with check (bucket_id = 'agent-photos');

-- ─── Done. Verify ────────────────────────────────────────────────────
-- select count(*) from public.agents;        -- expect: 0
-- \d public.listings                          -- agent_id column present
-- select id from storage.buckets;             -- expect agent-photos in list
