-- =====================================================================
-- REGLA · Slice 2.5 — Lead routing
-- Paste into Supabase Dashboard → SQL Editor → Run.
-- Idempotent.
-- =====================================================================

alter table public.inquiries
    add column if not exists assigned_agent_id bigint references public.agents(id) on delete set null;

create index if not exists inquiries_assigned_idx on public.inquiries (assigned_agent_id);

-- Optional: an audit log of routing decisions, kept lightweight.
create table if not exists public.lead_assignments (
    id              bigint generated by default as identity primary key,
    inquiry_id      bigint not null references public.inquiries(id) on delete cascade,
    agent_id        bigint references public.agents(id) on delete set null,
    reason          text not null check (reason in ('listing_owner','round_robin','manual','unassigned')),
    actor_id        uuid references auth.users(id),
    created_at      timestamptz not null default now()
);

create index if not exists lead_assignments_inquiry_idx on public.lead_assignments (inquiry_id, created_at desc);

alter table public.lead_assignments enable row level security;
drop policy if exists "lead_assignments: auth manage" on public.lead_assignments;
create policy "lead_assignments: auth manage" on public.lead_assignments
    for all to authenticated using (true) with check (true);

-- ─── Done. Verify ────────────────────────────────────────────────────
-- select column_name from information_schema.columns
--   where table_schema='public' and table_name='inquiries' and column_name='assigned_agent_id';
-- select count(*) from public.lead_assignments;  -- expect: 0
