-- =====================================================================
-- REGLA · Slice 2.6 — Deal documents
-- Paste into Supabase Dashboard → SQL Editor → Run.
-- Idempotent.
-- =====================================================================

create table if not exists public.deal_documents (
    id              bigint generated by default as identity primary key,
    inquiry_id      bigint references public.inquiries(id) on delete cascade,
    listing_id      bigint references public.listings(id) on delete cascade,
    category        text not null check (category in (
        'offer','contract','identity','financials','disclosure',
        'floorplan','title','tax','insurance','correspondence','other'
    )),
    label           text,
    filename        text not null,
    storage_path    text not null,
    mime_type       text not null,
    size_bytes      bigint not null check (size_bytes > 0),
    uploaded_by     uuid references auth.users(id),
    created_at      timestamptz not null default now(),
    constraint deal_documents_at_least_one_parent
        check (inquiry_id is not null or listing_id is not null)
);

create index if not exists deal_documents_inquiry_idx on public.deal_documents (inquiry_id, created_at desc);
create index if not exists deal_documents_listing_idx on public.deal_documents (listing_id, created_at desc);

alter table public.deal_documents enable row level security;

drop policy if exists "deal_documents: auth manage" on public.deal_documents;
create policy "deal_documents: auth manage" on public.deal_documents
    for all to authenticated using (true) with check (true);

-- Private storage bucket (NOT public; signed URLs for downloads).
insert into storage.buckets (id, name, public)
values ('deal-documents', 'deal-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "deal-documents: auth read"   on storage.objects;
drop policy if exists "deal-documents: auth manage" on storage.objects;

create policy "deal-documents: auth read" on storage.objects
    for select to authenticated using (bucket_id = 'deal-documents');

create policy "deal-documents: auth manage" on storage.objects
    for all to authenticated
    using (bucket_id = 'deal-documents')
    with check (bucket_id = 'deal-documents');

-- ─── Done. Verify ────────────────────────────────────────────────────
-- select count(*) from public.deal_documents;     -- expect: 0
-- select id, public from storage.buckets where id = 'deal-documents';
