-- =====================================================================
-- REGLA · Slice 2.X — Listing videos (Remotion-rendered marketing reels)
-- Paste into Supabase Dashboard → SQL Editor → Run.
-- Idempotent.
-- =====================================================================

create table if not exists public.listing_videos (
    id                bigint generated by default as identity primary key,
    listing_id        bigint not null references public.listings(id) on delete cascade,
    format            text   not null check (format in ('landscape','vertical','square')),
    storage_path      text   not null,
    duration_seconds  smallint not null default 24,
    file_size_bytes   bigint,
    rendered_at       timestamptz not null default now(),
    unique (listing_id, format)
);

create index if not exists listing_videos_listing_idx on public.listing_videos (listing_id);

-- ─── RLS ─────────────────────────────────────────────────────────────

alter table public.listing_videos enable row level security;

drop policy if exists "listing_videos: public read" on public.listing_videos;
drop policy if exists "listing_videos: auth manage" on public.listing_videos;

create policy "listing_videos: public read" on public.listing_videos
    for select using (true);

create policy "listing_videos: auth manage" on public.listing_videos
    for all to authenticated using (true) with check (true);

-- ─── Storage bucket for rendered reels ───────────────────────────────

insert into storage.buckets (id, name, public)
values ('listing-videos', 'listing-videos', true)
on conflict (id) do nothing;

drop policy if exists "listing-videos: public read" on storage.objects;
drop policy if exists "listing-videos: auth manage" on storage.objects;

create policy "listing-videos: public read" on storage.objects
    for select using (bucket_id = 'listing-videos');

create policy "listing-videos: auth manage" on storage.objects
    for all to authenticated
    using (bucket_id = 'listing-videos')
    with check (bucket_id = 'listing-videos');

-- ─── Done. Verify ────────────────────────────────────────────────────
-- select count(*) from public.listing_videos;     -- expect: 0
-- select id from storage.buckets where id = 'listing-videos';
