-- Slice 3.2 — Saved searches + email alerts
--
-- Email-only saved searches (no account system). Public users provide an
-- email and receive a daily digest of new listings matching their criteria.
-- Each row carries an unsubscribe token so digest emails can include a
-- one-click signed-URL unsubscribe link.

create table if not exists public.saved_searches (
    id              bigint generated by default as identity primary key,
    email           text not null,
    criteria        jsonb not null default '{}'::jsonb,
    label           text,                                       -- optional human label
    unsubscribe_token text not null default encode(gen_random_bytes(24), 'hex'),
    last_sent_at    timestamptz,                                -- last successful digest send
    confirmed       boolean not null default true,              -- v0: opt-in implicit; v1 may add confirm step
    active          boolean not null default true,
    created_at      timestamptz not null default now()
);

create index if not exists saved_searches_email_idx        on public.saved_searches (email);
create index if not exists saved_searches_active_idx       on public.saved_searches (active) where active = true;
create unique index if not exists saved_searches_token_idx on public.saved_searches (unsubscribe_token);

-- Sent-digest log (audit trail; one row per saved-search per send)
create table if not exists public.search_digests (
    id              bigint generated by default as identity primary key,
    saved_search_id bigint not null references public.saved_searches(id) on delete cascade,
    listing_count   integer not null default 0,
    sent_at         timestamptz not null default now(),
    error           text                                          -- non-null if Resend errored
);

create index if not exists search_digests_search_idx on public.search_digests (saved_search_id, sent_at desc);

-- ─── RLS ─────────────────────────────────────────────────────────────

alter table public.saved_searches enable row level security;
alter table public.search_digests enable row level security;

-- Public can only INSERT (the "Save this search" form). Reads/updates/deletes
-- happen through service-role from the cron + unsubscribe endpoints.
drop policy if exists "saved_searches: anon insert" on public.saved_searches;
create policy "saved_searches: anon insert" on public.saved_searches
    for insert to anon with check (true);

drop policy if exists "saved_searches: auth all"   on public.saved_searches;
create policy "saved_searches: auth all" on public.saved_searches
    for all to authenticated using (true) with check (true);

drop policy if exists "search_digests: auth all"   on public.search_digests;
create policy "search_digests: auth all" on public.search_digests
    for all to authenticated using (true) with check (true);

-- ─── Verify queries ──────────────────────────────────────────────────
--
-- select count(*) from public.saved_searches;
-- select count(*) from public.search_digests;
