-- Slice 3.3 — Lead scoring v0
--
-- Anonymous visitor sessions are tracked client-side via a cookie UUID
-- (`regla_sid`). When the visitor submits a public inquiry form, the
-- session_uuid is persisted on the inquiries row, linking pre-form
-- behavior to the lead.

-- 1. Anonymous behavior log
create table if not exists public.lead_events (
    id              bigint generated by default as identity primary key,
    session_uuid    uuid not null,
    kind            text not null check (kind in ('listing_view', 'page_view', 'form_submit')),
    property_id     bigint references public.listings(id) on delete set null,
    metadata        jsonb default '{}'::jsonb,
    created_at      timestamptz not null default now()
);

create index if not exists lead_events_session_idx  on public.lead_events (session_uuid, created_at);
create index if not exists lead_events_property_idx on public.lead_events (property_id) where property_id is not null;
create index if not exists lead_events_created_idx  on public.lead_events (created_at desc);

-- 2. Link inquiries to their session
alter table public.inquiries add column if not exists session_uuid uuid;
create index if not exists inquiries_session_idx on public.inquiries (session_uuid) where session_uuid is not null;

-- 3. Score view — joins inquiries to their pre-form behavior
--
-- Formula:
--   properties_viewed * 5         (each unique listing viewed; cap ~50)
--   + distinct_days * 10          (return visits proxy; cap ~30)
--   + 50                          (form submission baseline)
-- Result clamped to [0, 100].
create or replace view public.lead_scores as
select
    i.id as inquiry_id,
    i.session_uuid,
    coalesce(stats.properties_viewed, 0) as properties_viewed,
    coalesce(stats.distinct_days, 0)     as distinct_days,
    least(
        100,
        50
        + coalesce(stats.properties_viewed, 0) * 5
        + coalesce(stats.distinct_days, 0) * 10
    ) as score
from public.inquiries i
left join lateral (
    select
        count(distinct e.property_id)             filter (where e.kind = 'listing_view' and e.property_id is not null) as properties_viewed,
        count(distinct date_trunc('day', e.created_at))                                                                 as distinct_days
    from public.lead_events e
    where e.session_uuid = i.session_uuid
      and e.created_at <= i.created_at  -- pre-submission behavior only
) stats on true;

-- ─── RLS ─────────────────────────────────────────────────────────────

alter table public.lead_events enable row level security;

drop policy if exists "lead_events: anon insert" on public.lead_events;
create policy "lead_events: anon insert" on public.lead_events
    for insert to anon with check (true);

drop policy if exists "lead_events: auth read"   on public.lead_events;
create policy "lead_events: auth read" on public.lead_events
    for select to authenticated using (true);

-- ─── Verify queries ──────────────────────────────────────────────────
--
-- select count(*) from public.lead_events;
-- select * from public.lead_scores order by score desc limit 10;
