-- =====================================================================
-- REGLA · 0012 — Mobile client app (QuintoAndar-style "propostas")
-- Paste into Supabase Dashboard → SQL Editor → Run.  Idempotent.
-- =====================================================================
-- Adds the tables behind the REGLA client app (apps/client) and the realtor
-- app (apps/realtor). Row shapes mirror packages/shared/src/types.ts:
--   client_profiles  ↔ ClientProfile      ("meu cadastro")
--   applications     ↔ Application        (proposta on a listing)
--   client_documents ↔ ClientDocument     (files in bucket 'client-documents')
--   favorites        ↔ Favorite
--
-- Roles: realtors = admins (public.is_admin(), 0010). Clients = any other
-- authenticated user.
--
-- What clients can already do via EXISTING policies (no change needed):
--   * read live listings      — "listings: public reads live" (0001) has no
--                                `to` role, so it applies to authenticated too
--   * read listing photos     — "photos: public reads" (0001), same reasoning
--   * send an inquiry         — "inquiries: public inserts" (0001), no role;
--                                SELECT stays admin-only (api.ts never selects back)
--   * book / list own visits  — "showings: visitor books own" + "showings:
--                                visitor reads own" (0010); api.bookVisit inserts
--                                type='private', status='scheduled', created_by=uid
-- =====================================================================

-- ─── 1. client_profiles ───────────────────────────────────────────────

create table if not exists public.client_profiles (
    user_id          uuid primary key references auth.users(id) on delete cascade,
    full_name        text not null,
    email            text not null,
    phone            text not null,
    cpf              text,
    birth_date       date,
    occupation       text,
    employment_type  text check (employment_type in
                         ('clt','autonomo','empresario','servidor','aposentado','estudante','outro')),
    monthly_income   bigint check (monthly_income >= 0),
    residents        smallint not null default 1 check (residents between 1 and 20),
    has_pets         boolean not null default false,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);

drop trigger if exists client_profiles_set_updated_at on public.client_profiles;
create trigger client_profiles_set_updated_at
    before update on public.client_profiles
    for each row execute function public.set_updated_at();

alter table public.client_profiles enable row level security;

drop policy if exists "client_profiles: owner select" on public.client_profiles;
drop policy if exists "client_profiles: owner insert" on public.client_profiles;
drop policy if exists "client_profiles: owner update" on public.client_profiles;
drop policy if exists "client_profiles: admin select" on public.client_profiles;

create policy "client_profiles: owner select" on public.client_profiles
    for select to authenticated using (user_id = auth.uid());

create policy "client_profiles: owner insert" on public.client_profiles
    for insert to authenticated with check (user_id = auth.uid());

create policy "client_profiles: owner update" on public.client_profiles
    for update to authenticated
    using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "client_profiles: admin select" on public.client_profiles
    for select to authenticated using (public.is_admin());

-- ─── 2. applications ("propostas") ────────────────────────────────────

create table if not exists public.applications (
    id              bigint generated by default as identity primary key,
    listing_id      bigint not null references public.listings(id) on delete cascade,
    -- FK to client_profiles (not auth.users) so PostgREST can embed
    -- `client_profiles(*)` from applications (api.fetchApplicationsForReview).
    user_id         uuid not null references public.client_profiles(user_id) on delete cascade,
    intent          text not null check (intent in ('rent','buy')),
    offered_price   bigint not null check (offered_price > 0),
    guarantee_type  text check (guarantee_type in
                        ('seguro_fianca','fiador','caucao','titulo_capitalizacao','sem_garantia')),
    move_in_date    date,
    message         text,
    status          text not null default 'submitted' check (status in
                        ('submitted','under_review','docs_requested','approved','rejected','withdrawn')),
    reviewer_note   text,
    reviewed_by     uuid references auth.users(id) on delete set null,
    inquiry_id      bigint references public.inquiries(id) on delete set null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists applications_user_idx    on public.applications (user_id, created_at desc);
create index if not exists applications_listing_idx on public.applications (listing_id);
create index if not exists applications_status_idx  on public.applications (status, created_at desc);
create index if not exists applications_inquiry_idx on public.applications (inquiry_id);
create index if not exists applications_reviewer_idx on public.applications (reviewed_by);

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at
    before update on public.applications
    for each row execute function public.set_updated_at();

-- 2a. Non-admins may only withdraw their own (still open) application.
create or replace function public.applications_guard_client_update()
returns trigger language plpgsql set search_path = public as $$
begin
    -- service role / SQL editor (no JWT) and realtors are unrestricted
    if auth.uid() is null or public.is_admin() then
        return new;
    end if;
    if new.status <> 'withdrawn'
       or old.status not in ('submitted','under_review','docs_requested')
       or (to_jsonb(new) - 'status' - 'updated_at') is distinct from (to_jsonb(old) - 'status' - 'updated_at')
    then
        raise exception 'clients can only withdraw an open application'
            using errcode = '42501';
    end if;
    return new;
end $$;

drop trigger if exists applications_guard_client_update on public.applications;
create trigger applications_guard_client_update
    before update on public.applications
    for each row execute function public.applications_guard_client_update();

-- 2b. Every new proposta becomes a CRM lead (stage 'offer') in the web admin.
create or replace function public.applications_create_inquiry()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    p   public.client_profiles%rowtype;
    msg text;
begin
    if new.inquiry_id is not null and public.is_admin() then
        return new;  -- realtor linked it to an existing lead explicitly
    end if;
    select * into p from public.client_profiles where user_id = new.user_id;
    msg := format(
        'Proposta #%s via app: %s de R$ %s%s%s%s',
        new.id,
        case new.intent when 'rent' then 'aluguel' else 'compra' end,
        replace(to_char(new.offered_price, 'FM999,999,999,999'), ',', '.'),  -- 8.500 (locale-independent)
        case when new.guarantee_type is not null then ' · garantia: ' || new.guarantee_type else '' end,
        case when new.move_in_date  is not null then ' · mudança: ' || to_char(new.move_in_date, 'DD/MM/YYYY') else '' end,
        case when coalesce(trim(new.message), '') <> '' then E'\n\n' || new.message else '' end
    );
    insert into public.inquiries (name, email, message, property_id, intent, stage)
    values (coalesce(p.full_name, 'Cliente app'), coalesce(p.email, ''), msg, new.listing_id, new.intent, 'offer')
    returning id into new.inquiry_id;
    return new;
end $$;
revoke all on function public.applications_create_inquiry() from public;

drop trigger if exists applications_create_inquiry on public.applications;
create trigger applications_create_inquiry
    before insert on public.applications
    for each row execute function public.applications_create_inquiry();

-- 2c. Keep the linked lead in sync: approved → closed_won; any status change
-- also bumps inquiries.last_activity_at (via 0002's update trigger).
create or replace function public.applications_sync_inquiry()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if new.inquiry_id is not null and new.status is distinct from old.status then
        update public.inquiries
           set stage = case when new.status = 'approved' then 'closed_won' else stage end
         where id = new.inquiry_id;
    end if;
    return null;
end $$;
revoke all on function public.applications_sync_inquiry() from public;

drop trigger if exists applications_sync_inquiry on public.applications;
create trigger applications_sync_inquiry
    after update of status on public.applications
    for each row execute function public.applications_sync_inquiry();

alter table public.applications enable row level security;

drop policy if exists "applications: owner insert" on public.applications;
drop policy if exists "applications: owner select" on public.applications;
drop policy if exists "applications: owner withdraw" on public.applications;
drop policy if exists "applications: admin all" on public.applications;

create policy "applications: owner insert" on public.applications
    for insert to authenticated
    with check (user_id = auth.uid() and status = 'submitted'
                and reviewed_by is null and reviewer_note is null);

create policy "applications: owner select" on public.applications
    for select to authenticated using (user_id = auth.uid());

-- Row-level gate; the guard trigger (2a) blocks every other column change.
create policy "applications: owner withdraw" on public.applications
    for update to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid() and status = 'withdrawn');

create policy "applications: admin all" on public.applications
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── 3. client_documents ──────────────────────────────────────────────

create table if not exists public.client_documents (
    id              bigint generated by default as identity primary key,
    user_id         uuid not null references auth.users(id) on delete cascade,
    application_id  bigint references public.applications(id) on delete set null,
    kind            text not null check (kind in
                        ('rg_cnh','cpf','comprovante_renda','comprovante_residencia',
                         'extrato_bancario','imposto_renda','outro')),
    filename        text not null,
    storage_path    text not null,
    mime_type       text not null,
    size_bytes      bigint not null check (size_bytes > 0),
    created_at      timestamptz not null default now()
);

create index if not exists client_documents_user_idx        on public.client_documents (user_id, created_at desc);
create index if not exists client_documents_application_idx on public.client_documents (application_id);

alter table public.client_documents enable row level security;

drop policy if exists "client_documents: owner select" on public.client_documents;
drop policy if exists "client_documents: owner insert" on public.client_documents;
drop policy if exists "client_documents: owner delete" on public.client_documents;
drop policy if exists "client_documents: admin select" on public.client_documents;

create policy "client_documents: owner select" on public.client_documents
    for select to authenticated using (user_id = auth.uid());

create policy "client_documents: owner insert" on public.client_documents
    for insert to authenticated
    with check (
        user_id = auth.uid()
        and storage_path like auth.uid()::text || '/%'
        and (application_id is null or exists (
            select 1 from public.applications a
            where a.id = application_id and a.user_id = auth.uid()))
    );

create policy "client_documents: owner delete" on public.client_documents
    for delete to authenticated using (user_id = auth.uid());

create policy "client_documents: admin select" on public.client_documents
    for select to authenticated using (public.is_admin());

-- Private bucket; objects live under `<auth.uid()>/<kind>/<ts>-<file>`
-- (see documentPath() in packages/shared/src/api.ts). Downloads use signed URLs.
insert into storage.buckets (id, name, public)
values ('client-documents', 'client-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "client-documents: owner insert" on storage.objects;
drop policy if exists "client-documents: owner select" on storage.objects;
drop policy if exists "client-documents: owner delete" on storage.objects;
drop policy if exists "client-documents: admin select" on storage.objects;

create policy "client-documents: owner insert" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'client-documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "client-documents: owner select" on storage.objects
    for select to authenticated
    using (bucket_id = 'client-documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "client-documents: owner delete" on storage.objects
    for delete to authenticated
    using (bucket_id = 'client-documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "client-documents: admin select" on storage.objects
    for select to authenticated
    using (bucket_id = 'client-documents' and public.is_admin());

-- ─── 4. favorites ─────────────────────────────────────────────────────

create table if not exists public.favorites (
    user_id     uuid not null references auth.users(id) on delete cascade,
    listing_id  bigint not null references public.listings(id) on delete cascade,
    created_at  timestamptz not null default now(),
    primary key (user_id, listing_id)
);

create index if not exists favorites_listing_idx on public.favorites (listing_id);

alter table public.favorites enable row level security;

drop policy if exists "favorites: owner all" on public.favorites;
create policy "favorites: owner all" on public.favorites
    for all to authenticated
    using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ─── 5. Grants (explicit; Supabase's default privileges usually cover this) ──

grant select, insert, update          on public.client_profiles  to authenticated;
grant select, insert, update          on public.applications     to authenticated;
grant select, insert, delete          on public.client_documents to authenticated;
grant select, insert, update, delete  on public.favorites        to authenticated;

-- ─── 6. Realtime (realtor app live-updates on new propostas / leads) ──

do $$
declare t text;
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
        foreach t in array array['applications', 'inquiries'] loop
            if not exists (
                select 1 from pg_publication_tables
                where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
            ) then
                execute format('alter publication supabase_realtime add table public.%I', t);
            end if;
        end loop;
    end if;
end $$;

-- ─── Done. Verify ─────────────────────────────────────────────────────
-- select count(*) from public.client_profiles;     -- expect 0
-- select id, public from storage.buckets where id = 'client-documents';  -- false
-- select tablename from pg_publication_tables where pubname = 'supabase_realtime';
