-- =====================================================================
-- REGLA · 0014 · QuintoAndar-style proposal lifecycle
-- Paste into Supabase SQL Editor → Run.  Idempotent.
--
--   client sends proposta (cadastro + CPF + renda + terms, NO documents)
--     → negotiation: each side may accept / counter / decline; whoever did
--       NOT make the latest offer must act (`awaiting`)
--     → accepted (agreed_price locked) → client uploads documents
--     → docs_review → realtor approves (lead closed_won) or asks for
--       corrections (docs_requested → client re-sends → docs_review)
--
-- Clients act only through the security-definer RPCs below; their direct
-- UPDATE stays limited to withdrawing (0012 guard trigger).
-- =====================================================================

-- ─── 1. applications: new statuses + negotiation columns ──────────────
alter table public.applications drop constraint if exists applications_status_check;
alter table public.applications add constraint applications_status_check check (status in (
    'submitted', 'under_review', 'negotiating', 'accepted',
    'docs_review', 'docs_requested', 'approved', 'rejected', 'withdrawn'));

alter table public.applications add column if not exists agreed_price bigint
    check (agreed_price is null or agreed_price > 0);
alter table public.applications add column if not exists awaiting text
    check (awaiting is null or awaiting in ('client', 'realtor'));

create index if not exists applications_awaiting_idx on public.applications (awaiting, updated_at desc)
    where awaiting is not null;

-- Whose turn a status implies. 'negotiating' is decided by the latest offer.
create or replace function public.proposal_awaiting_for(p_status text)
returns text language sql immutable as $$
    select case
        when p_status in ('submitted', 'under_review', 'docs_review') then 'realtor'
        when p_status in ('accepted', 'docs_requested')                then 'client'
        else null
    end
$$;

update public.applications
   set awaiting = public.proposal_awaiting_for(status)
 where status <> 'negotiating' and awaiting is distinct from public.proposal_awaiting_for(status);

create or replace function public.applications_set_awaiting()
returns trigger language plpgsql set search_path = public as $$
begin
    if tg_op = 'INSERT' then
        new.awaiting := coalesce(public.proposal_awaiting_for(new.status), 'realtor');
    elsif new.status is distinct from old.status and new.status <> 'negotiating' then
        new.awaiting := public.proposal_awaiting_for(new.status);
    end if;
    return new;
end $$;

drop trigger if exists applications_set_awaiting on public.applications;
create trigger applications_set_awaiting
    before insert or update on public.applications
    for each row execute function public.applications_set_awaiting();

-- The 0012 guard lets clients only withdraw. Calls made from inside the
-- security-definer RPCs below run as the function owner, not `authenticated`.
create or replace function public.applications_guard_client_update()
returns trigger language plpgsql set search_path = public as $$
begin
    if auth.uid() is null or public.is_admin() or current_user <> 'authenticated' then
        return new;
    end if;
    if new.status <> 'withdrawn'
       or old.status not in ('submitted', 'under_review', 'negotiating', 'accepted', 'docs_review', 'docs_requested')
       or (to_jsonb(new) - 'status' - 'updated_at' - 'awaiting') is distinct from (to_jsonb(old) - 'status' - 'updated_at' - 'awaiting')
    then
        raise exception 'clients can only withdraw an open application'
            using errcode = '42501';
    end if;
    return new;
end $$;

-- ─── 2. application_offers: the negotiation timeline ──────────────────
create table if not exists public.application_offers (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references public.applications(id) on delete cascade,
    author          text not null check (author in ('client', 'realtor')),
    author_id       uuid references auth.users(id) on delete set null,
    price           bigint not null check (price > 0),
    guarantee_type  text check (guarantee_type in
                        ('seguro_fianca','fiador','caucao','titulo_capitalizacao','sem_garantia')),
    move_in_date    date,
    message         text,
    created_at      timestamptz not null default now()
);

create index if not exists application_offers_app_idx on public.application_offers (application_id, created_at);
create index if not exists application_offers_author_idx on public.application_offers (author_id);

alter table public.application_offers enable row level security;

drop policy if exists "application_offers: owner select" on public.application_offers;
drop policy if exists "application_offers: admin all" on public.application_offers;

create policy "application_offers: owner select" on public.application_offers
    for select to authenticated
    using (exists (select 1 from public.applications a
                   where a.id = application_id and a.user_id = auth.uid()));

create policy "application_offers: admin all" on public.application_offers
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant select on public.application_offers to authenticated;

-- First offer = the proposta itself.
create or replace function public.applications_initial_offer()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.application_offers
        (application_id, author, author_id, price, guarantee_type, move_in_date, message)
    values (new.id, 'client', new.user_id, new.offered_price, new.guarantee_type, new.move_in_date, new.message);
    return null;
end $$;
revoke all on function public.applications_initial_offer() from public;

drop trigger if exists applications_initial_offer on public.applications;
create trigger applications_initial_offer
    after insert on public.applications
    for each row execute function public.applications_initial_offer();

-- Backfill: proposals created before 0014 get their opening offer.
insert into public.application_offers (application_id, author, author_id, price, guarantee_type, move_in_date, message, created_at)
select a.id, 'client', a.user_id, a.offered_price, a.guarantee_type, a.move_in_date, a.message, a.created_at
from public.applications a
where not exists (select 1 from public.application_offers o where o.application_id = a.id);

-- ─── 3. RPCs ──────────────────────────────────────────────────────────

-- Locks the application row and returns it with the caller's party
-- ('client' / 'realtor'). Raises 42501 unless the caller is the realtor or
-- the owning client.
create or replace function public.proposal_party(p_app public.applications)
returns text language plpgsql stable security definer set search_path = public as $$
begin
    if auth.uid() is null then
        raise exception 'not authenticated' using errcode = '42501';
    end if;
    if public.is_admin() then
        return 'realtor';
    elsif p_app.user_id = auth.uid() then
        return 'client';
    end if;
    raise exception 'not your application' using errcode = '42501';
end $$;
revoke all on function public.proposal_party(public.applications) from public;

-- Counter-offer: new terms from whoever's turn it is. Missing optional
-- terms are inherited from the latest offer.
create or replace function public.proposal_counter(
    p_application_id bigint,
    p_price          bigint,
    p_message        text default null,
    p_guarantee_type text default null,
    p_move_in_date   date default null)
returns public.application_offers
language plpgsql security definer set search_path = public as $$
declare
    app   public.applications;
    party text;
    last  public.application_offers;
    offer public.application_offers;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if app.status not in ('submitted', 'under_review', 'negotiating') or app.awaiting is distinct from party then
        raise exception 'it is not your turn to counter' using errcode = '42501';
    end if;
    if p_price is null or p_price <= 0 then
        raise exception 'price must be positive' using errcode = '22023';
    end if;

    select * into last from public.application_offers
     where application_id = p_application_id order by created_at desc, id desc limit 1;

    insert into public.application_offers (application_id, author, author_id, price, guarantee_type, move_in_date, message)
    values (p_application_id, party, auth.uid(), p_price,
            coalesce(p_guarantee_type, last.guarantee_type),
            coalesce(p_move_in_date, last.move_in_date),
            nullif(trim(p_message), ''))
    returning * into offer;

    update public.applications
       set status = 'negotiating',
           awaiting = case party when 'client' then 'realtor' else 'client' end
     where id = p_application_id;
    return offer;
end $$;

-- Accept the latest offer (must be the other party's).
create or replace function public.proposal_accept(p_application_id bigint)
returns public.applications
language plpgsql security definer set search_path = public as $$
declare
    app  public.applications;
    party text;
    last public.application_offers;
    res  public.applications;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if app.status not in ('submitted', 'under_review', 'negotiating') or app.awaiting is distinct from party then
        raise exception 'it is not your turn to accept' using errcode = '42501';
    end if;
    select * into last from public.application_offers
     where application_id = p_application_id order by created_at desc, id desc limit 1;
    if last.author = party then
        raise exception 'cannot accept your own offer' using errcode = '42501';
    end if;

    update public.applications
       set status = 'accepted',
           agreed_price = last.price,
           guarantee_type = coalesce(last.guarantee_type, guarantee_type),
           move_in_date = coalesce(last.move_in_date, move_in_date),
           reviewed_by = case when party = 'realtor' then auth.uid() else reviewed_by end
     where id = p_application_id
    returning * into res;
    return res;
end $$;

-- Decline: realtor → rejected (with note), client → withdrawn.
create or replace function public.proposal_decline(p_application_id bigint, p_note text default null)
returns public.applications
language plpgsql security definer set search_path = public as $$
declare
    app public.applications;
    party text;
    res public.applications;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if app.status in ('approved', 'rejected', 'withdrawn') then
        raise exception 'application is already closed' using errcode = '42501';
    end if;
    if party = 'realtor' then
        update public.applications
           set status = 'rejected', reviewer_note = nullif(trim(p_note), ''), reviewed_by = auth.uid()
         where id = p_application_id
        returning * into res;
    else
        update public.applications set status = 'withdrawn'
         where id = p_application_id
        returning * into res;
    end if;
    return res;
end $$;

-- Client finished uploading documents → realtor reviews them.
create or replace function public.proposal_docs_sent(p_application_id bigint)
returns public.applications
language plpgsql security definer set search_path = public as $$
declare
    app public.applications;
    party text;
    res public.applications;
begin
    select * into app from public.applications where id = p_application_id for update;
    if not found then
        raise exception 'application not found' using errcode = 'P0002';
    end if;
    party := public.proposal_party(app);
    if party <> 'client' or app.status not in ('accepted', 'docs_requested') then
        raise exception 'documents can only be sent after acceptance' using errcode = '42501';
    end if;
    update public.applications set status = 'docs_review'
     where id = p_application_id
    returning * into res;
    return res;
end $$;

revoke all on function public.proposal_counter(bigint, bigint, text, text, date) from public;
revoke all on function public.proposal_accept(bigint) from public;
revoke all on function public.proposal_decline(bigint, text) from public;
revoke all on function public.proposal_docs_sent(bigint) from public;
grant execute on function public.proposal_counter(bigint, bigint, text, text, date) to authenticated;
grant execute on function public.proposal_accept(bigint) to authenticated;
grant execute on function public.proposal_decline(bigint, text) to authenticated;
grant execute on function public.proposal_docs_sent(bigint) to authenticated;

-- ─── 4. Realtime: offers stream to both apps ──────────────────────────
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (select 1 from pg_publication_tables
                       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'application_offers')
    then
        alter publication supabase_realtime add table public.application_offers;
    end if;
end $$;
